#!/usr/bin/env bash
APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"

APP_ID="$(openssl rand -hex 32)"
APP_KEY="$(openssl rand -hex 32)"
APP_SECRET="$(openssl rand -hex 32)"

sed -i "s|APP_ID=EXAMPLE|APP_ID=$(openssl rand -hex 16)|g" ${APP_DATA_DIR}/data/.env
sed -i "s|APP_KEY=EXAMPLE|APP_KEY=base64:$(openssl rand -base64 32)|g" ${APP_DATA_DIR}/data/.env
sed -i "s|PUSHER_APP_ID=EXAMPLE|PUSHER_APP_ID=${APP_ID}|g" ${APP_DATA_DIR}/data/.env
sed -i "s|PUSHER_APP_KEY=EXAMPLE|PUSHER_APP_KEY=${APP_KEY}|g" ${APP_DATA_DIR}/data/.env
sed -i "s|PUSHER_APP_SECRET=EXAMPLE|PUSHER_APP_SECRET=${APP_SECRET}|g" ${APP_DATA_DIR}/data/.env

sed -i "s|SOKETI_DEFAULT_APP_ID=EXAMPLE|SOKETI_DEFAULT_APP_ID=${APP_ID}|g" ${APP_DATA_DIR}/data/.env
sed -i "s|SOKETI_DEFAULT_APP_KEY=EXAMPLE|SOKETI_DEFAULT_APP_KEY=${APP_KEY}|g" ${APP_DATA_DIR}/data/.env
sed -i "s|SOKETI_DEFAULT_APP_SECRET=EXAMPLE|SOKETI_DEFAULT_APP_SECRET=${APP_SECRET}|g" ${APP_DATA_DIR}/data/.env