version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_ID}_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: caddy:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/Caddyfile:/etc/caddy/Caddyfile
    environment:
      APP_ID: ${APP_ID}
    depends_on:
      - backend
      - frontend

  backend:
    image: ghcr.io/evroon/bracket-backend
    restart: on-failure
    environment:
      ENVIRONMENT: PRODUCTION
      CORS_ORIGINS: http://${APP_DOMAIN}:${APP_PROXY_PORT}
      PG_DSN: postgresql://bracket:bracket@${APP_ID}_db_1:5432/bracket
      ADMIN_EMAIL: root@umbrel.local
      ADMIN_PASSWORD: p@ssw0rd
      JWT_SECRET: ${APP_SEED}
      ALLOW_INSECURE_HTTP_SSO: "false"
    volumes:
      - ${APP_DATA_DIR}/data/static:/app/static
    depends_on:
      - db

  frontend:
    image: ghcr.io/evroon/bracket-frontend
    restart: on-failure
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://${APP_DOMAIN}:${APP_PROXY_PORT}/api/
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: 10000000-ffff-ffff-ffff-000000000001

  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: bracket
      POSTGRES_PASSWORD: bracket
      POSTGRES_USER: bracket
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data