version: '3.8'

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_ID}_server_1
      APP_PORT: 8102
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/coollabsio/coolify:latest@sha256:f946e3ef419cfdf081af930946b416287d12e751f479d0411c80fb2614cf6eef
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_HOST: ${APP_DOMAIN}
      APP_PORT: 8102
      DB_USERNAME: coolify
      DB_PASSWORD: coolify
      DB_DATABASE: coolify
      DB_HOST: ${APP_ID}_db_1
      DB_PORT: 5432
      REDIS_HOST: ${APP_ID}_redis_1
      REDIS_PASSWORD: coolify
      ROOT_USERNAME: root
      ROOT_USER_EMAIL: root@umbrel.local
      ROOT_USER_PASSWORD: p@ssw0rd
      PUSHER_BACKEND_HOST: ${APP_ID}_pusher_1
      PHP_MEMORY_LIMIT: 128M
      PHP_FPM_PM_CONTROL: dynamic
      PHP_FPM_PM_START_SERVERS: 1
      PHP_FPM_PM_MIN_SPARE_SERVERS: 1
      PHP_FPM_PM_MAX_SPARE_SERVER: 10
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/data/.env
        target: /var/www/html/.env
        read_only: true
      - ${APP_DATA_DIR}/data/coolify/ssh:/var/www/html/storage/app/ssh
      - ${APP_DATA_DIR}/data/coolify/backups:/var/www/html/storage/app/backups
      - ${APP_DATA_DIR}/data/coolify/services:/var/www/html/storage/app/services
      - ${APP_DATA_DIR}/data/coolify/databases:/var/www/html/storage/app/databases
      - ${APP_DATA_DIR}/data/coolify/applications:/var/www/html/storage/app/applications
      - ${APP_DATA_DIR}/data/coolify/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance
    env_file:
      - ${APP_DATA_DIR}/data/.env
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pusher:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: coolify
      POSTGRES_DB: coolify
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U coolify", "-d", "coolify" ]
      interval: 5s
      retries: 10
      timeout: 2s

  redis:
    image: redis:7
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: coolify
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s

  pusher:
    image: ghcr.io/coollabsio/coolify-realtime:1.0.5
    volumes:
      - ${APP_DATA_DIR}/data/coolify/ssh:/var/www/html/storage/app/ssh
    environment:
      SOKETI_DEBUG: false
    env_file:
      - ${APP_DATA_DIR}/data/.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 2s